language: node_js
node_js:
- '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
deploy:
  provider: heroku
  api_key:
    secure: VROUDWEmHyMUXXUWzljE7R3ipYkUfoI2Npshx6lXEDKreDq14MeyEuShVczPauwzzS+FXH+1+vdKm93s1qqQ+cifRKeOLA3g8Zpq9v+7fuA+doqKyURiIpUTBgKHYyKabNpMJIjO1XlvNHuRCRewUrv+GDJmdJJR6ToGMCD3vofgp/MUBfFbfX3PZVwy30Lwi5qON8GY1qaIeNfG6aGyNhNXTp7KWi86i3RqvJs1Z0sbO2M1yhWpQTq0x7hqak+QauO71qpFujiylQKZyj9YsgSRcqH2cp/MU/aiKAhHBF1JKkR5v08f9diqx+FuHhJk2NVOb1BVRoBFESkdD+Vv+a4F+OMPeGBmyNtAKAXHomJVCFpQVIQaWEz3IUd36aFmayHp9ssyY/75kan50NGIU09I08NVd4g7LpnIQ+DBn7Up9JU8unbCtc+p3422VTVpKGb22ERKQE2fWyTfnuS5/dvcSsLNRAcIBVZ49MZ3uIEDeAz1oN1kjq0o781bjt/Sg1x7aRKYRvkgnjHuFT5MPpM2RC/NJ1/5TBX7HoppxeEaXP1qMlVAVBhcbJrE4btzm4H20/van+e95HjcIHtPiYCvR7qg9vXj6d2oyHZ2iNKM5i9jC1JRa0Gry3KO4msUKmQlCFToGOqkiaJgIhi1PJZCmT8hYzygmZhMSQHR5/w=
  app: tft-tools
  on:
    repo: jacgrady1/tft_tool
